
services:
    db:
      image : postgres:16
      container_name : postgres_project
      restart : always
      ports :
       - "5432:5432"
      
      environment : 
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD : 454675
        POSTGRES_DB: project_management
      volumes : 
        - db_data:/var/lib/postgresql/data


volumes:
  db_data: